# Generated by Django 4.0.2 on 2022-07-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecpts',
            name='tax',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesrecpts',
            name='tax1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesrecpts',
            name='tax3',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
