# Generated by Django 4.0.2 on 2022-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_salesrecpts_tax_alter_salesrecpts_tax1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecpts',
            name='tax2',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
